stocks = ['ACC', 'ADANIENT', 'ADANIPORTS', 'AMBUJACEM', 'ASIANPAINT', 'AUROPHARMA', 'AXISBANK', 'BAJAJ-AUTO', 'BAJAJFINSV', 'BAJFINANCE',
          'BHARTIARTL', 'BHEL', 'BPCL', 'BRITANNIA', 'CIPLA', 'COALINDIA', 'COLPAL', 'CONCOR', 'DABUR', 'DIVISLAB', 'DLF', 'DRREDDY',
          'EICHERMOT', 'GAIL', 'GODREJCP', 'GRASIM', 'HCLTECH', 'HDFC', 'HDFCBANK', 'HDFCLIFE', 'HEROMOTOCO', 'HINDALCO', 'HINDPETRO',
          'HINDUNILVR', 'ICICIBANK', 'INDUSINDBK', 'INFY', 'IOC', 'ITC', 'JSWSTEEL', 'KOTAKBANK', 'L&TFH', 'LT', 'M&M', 'MARUTI', 'NESTLEIND',
          'NTPC', 'ONGC', 'POWERGRID', 'RELIANCE', 'SBILIFE', 'SBIN', 'SHREECEM', 'SUNPHARMA', 'TATACONSUM', 'TATAMOTORS', 'TATASTEEL',
          'TCS', 'TECHM', 'TITAN', 'TORNTPHARM', 'TORNTPOWER', 'TVSMOTOR', 'UBL', 'ULTRACEMCO', 'UPL', 'VEDL', 'WIPRO', 'ZEEL', 'BHARTIINFRA',
          'BIOCON', 'CADILAHC', 'CANBK', 'CHOLAFIN', 'DIXON', 'ESCORTS', 'FEDERALBNK', 'HDFCAMC', 'IDFCFIRSTB', 'IGL', 'INDIGO', 'MGL', 'MRF',
          'NATIONALUM', 'NAUKRI', 'PETRONET', 'PFC', 'PIDILITIND', 'RAMCOCEM', 'SRTRANSFIN', 'TATAELXSI', 'UBL', 'LTI', 'TATACONSUM', 'MINDTREE']
